### PR TITLE
Issue#50

### PR DESCRIPTION
**Pull request by ccruz07**
Topic 5 topics created.

### CODE REVIEW

**Comment by ccruz07** [comment]
Please review and merge if ready

**Comment by ccruz07** [comment]
changed base branch to staging

**Comment by jonwalz** [comment]
I really like what you did with all the descriptions on the site. It sounds like your background comes in very handy for the purpose of this site!

The addition of hashtags to the handlebars template isn't quite correct and is a breaking change. I do like the hashtags you chose though! I will be removing those lines to make the site function again and lets discuss a way to add them to the functionality of the site!

**Comment by jonwalz** [comment]
Also, be sure to test in the browser before submitting pull request to discover these bugs.

**Comment by ccruz07** [comment]
Ok thanks, I wasn't sure about adding the actual hashtag sign, so please
make correction. I'm also adding a bit of description in the starting point
box. Just to tell users what this site is all about and encourage them to
post issues that we'll pull for our top 5 topics. Just a simple text. I'll
send it up in a few minutes.

**Pull request merged**
