### PR TITLE
Issue#46 submit button

### PR DESCRIPTION
**Pull request by ccruz07**
Submit button for the comment form goes to Twitter, but the form contents does not.

### CODE REVIEW

**Comment by ccruz07** [comment]
Don't understand what the conflict is here, did not push to master

**Comment by djado** [comment]
Git is picky. The best way to avoid (big) conflicts is to always pull down the latest before you begin work on a new branch.

I just noticed that you are trying to merge to master here. Look to the top of the page to the right of the green "Open" icon.

**Comment by ccruz07** [comment]
This is strange why it says merge to master, when I pushed it to the branch??? I went back and tried to pull down the latest version of master, had to clone it and now have new updates in Atom.

**Comment by djado** [comment]
It's easy to miss. When you are opening a pull request, there are two drop-down menu items. One of them needs to be changed from 'master' to 'staging'. I think it's the one on the left.

**Pull request merged**
