### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by ccruz07**
just added some text to starting point issue box for user info. will create the issue for backlog

### CODE REVIEW

**Comment by djado** [comment]
You are proposing a merge from staging into master.
I think what you want is to merge your branch into staging.

**Comment by ccruz07** [comment]
This back and forth with staging is confusing. Hope it is correct this time.  thx

**Comment by djado** [comment]
Sorry Cheryl. This looks backward to me.
I was going to just edit your PR and merge it myself but it actually won't let me do it.
All I can recommend is to read the instructions carefully before you submit.

**Comment by ccruz07** [comment]
ok not clear on what you mean- what looks backward. this staging is too confusing

**Comment by jonwalz** [comment]
Think of staging as the master before the master. In production, staging is where we test before deployment to world. In this context we want to pretend staging is master until presentation day. 
Up where is says:
    ccruz07  wants to merge 5 commits into issue#50 from staging
We need to change it to say:
    ccruz07  wants to merge 5 commits into staging from issue#50

Hit the edit button and just switch them around.

**Comment by jonwalz** [comment]
Oops, never mind. I guess you cant do it that way. Try resubmitting as a new pull request and just be sure the first dropdown says staging.

**Pull request merged**
